version: 0.2

env:
  git-credential-helper: yes
  variables:
    IMAGE_REPO_NAME: mebly_nginx # ECR Repository명
    AWS_ACCOUNT_ID: 150291371252 # AWS AccountID
    #CONTAINER_NAME: nginx-simple-container # ECS에서 사용할 컨테이너명
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - CODEBUILD_RESOLVED_SOURCE_VERSION="${CODEBUILD_RESOLVED_SOURCE_VERSION:-$IMAGE_TAG}"
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - echo Build stage successfully completed on `date`
      
      - echo Change manifest
      - git clone https://git-codecommit.ap-northeast-2.amazonaws.com/v1/repos/Mebly_manifest
      - cd ./Mebly_manifest
      - sed -i s/$IMAGE_REPO_NAME:.*/$IMAGE_REPO_NAME:$IMAGE_TAG/g ./nginx-deployment.yaml
      
      - git add .
      - git commit -m "change ${IMAGE_REPO_NAME} tag ${IMAGE_TAG}"
      - git push origin master